federation_version: 2
subgraphs:
  product:
    routing_url: http://localhost:4001/
    schema:
      subgraph_url: http://localhost:4001/
  review:
    routing_url: http://localhost:4002/
    schema:
      subgraph_url: http://localhost:4002/
